auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 48
  max_line_size: 256KB
  max_query_length: 721h
  max_query_lookback: 720h
  max_streams_per_user: 0
  max_global_streams_per_user: 0

# クエリフロントエンド設定
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

# チャンクキャッシュ設定  
chunk_store_config:
  max_look_back_period: 720h

# テーブル管理設定
table_manager:
  retention_deletes_enabled: false
  retention_period: 720h



